language: r
pandoc_version: 1.19.2.1

script:
  Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
  Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_CI_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: docs
  keep_history: true
  on:
    branch: master
   
sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
